spring.application.name=hotel

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

#Criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

#Mostrar no console os comandos SQL que o Spring está executando
spring.jpa.show-sql=true

#Formata o SQL no console para ficar mais facil de ler
spring.jpa.properties.hibernate.format_sql=true